# Generated by Django 4.0.5 on 2022-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.IntegerField()),
                ('user_type', models.CharField(blank=True, choices=[('user', 'User'), ('plumber', 'Plumber'), ('admin', 'Admin')], max_length=32, null=True)),
                ('language', models.CharField(blank=True, choices=[('uzbek', 'Uzbek'), ('russian', 'Russian')], max_length=15, null=True)),
            ],
        ),
    ]
