# Generated by Django 4.0.5 on 2022-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
